---
title: "06-mapping-data"
author: "Jack Sylvia"
date: "2/7/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(maps)
library(tidyverse)

state_df <- ggplot2::map_data("state")
ggplot(data = state_df,
            mapping = aes(x = long, y = lat,
                          group = group)) +
  geom_polygon(fill = "red") +
  coord_map() +
  xlab("") +
  ylab("") +
  theme_void()
```

```{r}
library(usdata)
state_stats
```

```{r}
state_stats <- state_stats %>% mutate(state = str_to_lower(state))
state_full <- left_join(state_df, state_stats, by = c("region" = "state"))
state_stats <- state_stats %>% as_tibble %>% mutate(pop_change = ((pop2010-pop2000)/pop2000)*100)

ggplot(data = state_full, aes(x = long, y = lat, group = group)) +
  geom_polygon(colour = "black", aes(fill = pop_change)) +
  coord_map(projection = "albers", lat0 = 39, lat1 = 45) +
  theme_void() +
  scale_fill_distiller(direction = 1)

## fermenter is for binning continuous
## brewer is for discrete colors
## distiller is for continuous variable
```

```{r}
active <- read_csv("https://raw.githubusercontent.com/iramler/stlawu_covid/main/slc_towns_active_cases.csv", n_max = 34)

tcases <- read_csv("https://raw.githubusercontent.com/iramler/stlawu_covid/main/slc_towns_total_cases.csv", n_max = 34)

active_long <- active %>% pivot_longer(5:ncol(active), names_to = "date", values_to = "cases")
## repeat for total cases
tcases_long <- tcases %>% pivot_longer(5:ncol(tcases), names_to = "date", values_to = "cases")
library(lubridate)

covid_df <- left_join(tcases_long, active_long,
                      by = c("date", "Order", "NAME")) %>%
  mutate(date = mdy(date)) %>%
  rename(total_cases = cases.x,
         active_cases = cases.y) %>%
  mutate(total_cases = if_else(is.na(total_cases),
                               true = 0, false = total_cases),
         active_cases = if_else(is.na(active_cases),
                                      true = 0, false = active_cases))
  

covid_SLC <- covid_df %>% filter(NAME == "St. Lawrence County")
covid_sub <- covid_df %>% filter(NAME != "St. Lawrence County")
```

```{r}
ggplot(data = covid_SLC, aes(x = date, y = active_cases)) +
  geom_line()
```



```{r}
library(sf)
shp <- read_sf("data/SLC_Civil_Boundaries_SHP/slc.shp") %>%
  st_transform(st_crs("+proj=longlat"))
shp

ggplot(data = shp) +
  geom_sf() +
  theme_void()

full_df <- left_join(shp, covid_sub, by = "NAME") %>%
  filter(date == max(date)) ## only plot cases on the most recent date

ggplot(data = full_df) +
  geom_sf(aes(fill = active_cases)) +
  theme_void() +
  scale_fill_distiller(direction = 1)
```


