---
title: "exercise-07"
author: "Jack Sylvia"
date: "3/6/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Exercise 1

```{r}
library(shiny)

ui <- fluidPage(
  textInput("name", "What's your name?"),
  textOutput("greeting")
)

```

```{r}
server <- function(input, output, session) {
  output$greeting <-
      renderText(paste0("Hello ", input$name))
}

shinyApp(ui, server)

```

```{r}
server2 <- function(input, output, server) {
  greeting <- reactive({
    paste0("Hello ", input$name)
  })
  output$greeting <- renderText(greeting())
}

shinyApp(ui, server2)
```

```{r}
server3 <- function(input, output, server) {
  output$greeting <- reactive({
    paste0("Hello ", input$name)
  })
}

shinyApp(ui, server3)
```

## Exercise 2

server1:

 a --
     \
      V
      c ----> e --> f (ends)
      ^       ^
     /       /
 b --    d --

server2:
x1
x2 }\
x3  |
    V
    x --
         \
          V
          z (ends)
          ^
         /
    y --
    ^
    |
y1 }/
y2

server3:

a --> b --> c --> d (ends)
