---
title: "Quiz2_TakeHome"
author: "Jack Sylvia"
date: "1/31/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Quiz 2 Take-Home

“All work presented is my own, and I have followed all rules for collaboration.” - Jack Sylvia

```{r, include = FALSE}
library(tidyverse)
library(readxl)
library(here)
df <- read_excel(here("data/slu_graduates_17_21.xlsx"))

## fixes error in the data
df <- df %>% mutate(across(everything(),
                           .fns = ~replace(., . ==  "STATS" , "STAT")))
df
```

## Question 1

```{r}
dfSTAT <- df %>%
  filter(major1 == "STAT" | major2 == "STAT" | major3 == "STAT") %>%
  pivot_longer(c(3,4,5,6,7,8),
               values_to = "discipline",
               names_to = "type") %>%
  filter(type == "major1" | type == "major2" | type == "major3") %>%
  filter(discipline != "STAT" & !is.na(discipline)) %>%
  group_by(discipline) %>%
  summarise(nstudents = n()) %>%
  arrange(desc(nstudents)) %>%
  mutate(discipline = fct_reorder(discipline, nstudents))

ggplot(data = dfSTAT, aes(x = discipline, y = nstudents)) +
  geom_bar(stat = 'identity') + coord_flip()

```

```{r, eval=FALSE, include=FALSE}
## Alternative way below

dfSTAT_Alternative <- df %>%
  pivot_longer(c(3,4,5,6,7,8),
               values_to = "discipline",
               names_to = "type") %>%
  filter(discipline == "STAT")

  semi_join(dfSTAT, dfSTAT_Alternative, by = "adm_id")

```

## Question 2

```{r}
dfFemale <- df %>%
  pivot_longer(c(3,4,5,6,7,8),
               values_to = "discipline",
               names_to = "type") %>%
  filter(type == "major1" | type == "major2" | type == "major3") %>%
  filter(!is.na(discipline))  %>%## keep anything that is not missing in discipline
  group_by(sex, discipline) %>%
  summarise(nstudents = n()) %>%
  ungroup() %>%
  group_by(discipline) %>%
  mutate(ntotal = sum(nstudents)) %>%
  mutate(proportion = nstudents/ntotal) %>%
  filter(ntotal >= 50) %>%
  filter(sex == "F") %>%
  mutate(discipline = fct_reorder(discipline, proportion)) %>%
  arrange(desc(proportion)) %>%
  mutate(higher = if_else(proportion > 0.5, true = "female", false = "male"))
  

ggplot(data = dfFemale, aes(x = reorder(discipline, proportion), y = proportion, colour = higher)) +
  geom_point(size=1.5) + 
  coord_flip() + 
  geom_segment(aes(x=discipline, xend=discipline, y=0.5, yend=proportion)) +
  ylab("Proportion of Female Majors in Past 5 Years") +
  xlab("discipline") +
  theme(legend.position = "none")
  
  
  
```

